# COMP47670 Assignment 1 - Autumn 2026/27
## Task 3: Data Analysis

**Student Name**: Ellen Lyons

**Student Number**: 26117753

In [1]:
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

### Load data
**Issue**: *Year Built* was loading with decimal places even though I got rid of them in Task 2. 

**Solution**: I read the pandas documentation for ``pd.read_csv`` and it has an argument to specify the ``dtype``, so I just re-specified the format I want.

In [2]:
# load in the ABT from task 2
df = pd.read_csv(
    "ABT.csv",
    index_col=0, # already assigned 'property index' as this
    parse_dates=["Date Sold"],
    dtype={"Year Built": "Int64"}
)

df.head()

,First Time Buyer,Size (sq ft),Garage,Garden,Sale Price (EUR),Date Sold,Year Built,Location,House Type,Number of Storeys,Number of Bedrooms,Number of Bathrooms
Property Reference,,,,,,,,,,,,
PROP-105204,Yes,1131,Yes,Yes,359086,2022-12-26,1984,Oak Park,Detached,1.5,3,1
PROP-105203,No,1941,Yes,Yes,734419,2022-12-25,2019,Porter Square,Detached,2.0,3,2
PROP-105202,No,1996,Yes,Yes,724835,2022-12-19,2021,Porter Square,Detached,2.0,3,2
PROP-105201,No,1463,Yes,Yes,446404,2022-12-18,2013,Avoca,Detached,1.5,3,2
PROP-105200,No,1660,Yes,Yes,554762,2022-12-17,2008,Brookville,Detached,2.0,3,2

In [4]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
Size (sq ft),1450.0,1422.711034,294.0,1058.25,1398.5,1701.0,3706.0,443.761325
Sale Price (EUR),1450.0,434333.88069,91929.0,322901.75,388854.5,508703.75,1632196.0,176370.546146
Date Sold,1450,2024-02-18 08:22:30.620689,2022-01-15 00:00:00,2023-04-11 00:00:00,2024-05-11 00:00:00,2025-04-09 00:00:00,2025-12-28 00:00:00,NaN
Year Built,1392.0,1981.265086,1885.0,1963.0,1979.0,2013.0,2022.0,31.766731
Number of Storeys,1450.0,1.335172,1.0,1.0,1.0,2.0,2.0,0.453577
Number of Bedrooms,1450.0,2.883448,1.0,2.0,3.0,3.0,5.0,0.730534
Number of Bathrooms,1450.0,1.529655,1.0,1.0,2.0,2.0,3.0,0.546792

### Future Work

I really liked the 'hotspot map' that this data scientist did: https://niallmartin.io/posts/data-analysis-dublin-property-trends/.
The locations in my dataset are made up/I wasn't given the exact coordinates of them, so I wasn't able to do this, but it would be an interesting visual in future.

Something else that came to mind for future work is to use a simple ML regression model to predict house prices. This data that I explored here could be used as training and test data to develop a model, and then use this model to estimate the price a house would have based on its type, location, number of bedrooms/bathrooms, if it has as garden/garage, etc!